### ISSUE TITLE
theme-triton: .css files missing

### ISSUE THREAD

**Issue by wwwutz** [adRn-s/parkour2#52]
```
# cat parkour_app/static/main-hub/ext/build/classic/theme-triton/resources/theme-triton-all.css
@import 'theme-triton-all_1.css';
@import 'theme-triton-all_2.css';
```
these files are missing, leading to:

```
2023/08/03 08:51:38 [error] 31947#0: *242 open() "/project/parkour/parkour2/parkour_app/staticfiles/main-hub/ext/build/classic/theme-triton/resources/theme-triton-all_2.css" failed (2: No such file or directory), client: 141.14.14.119, server: https-pk.molgen.mpg.de, request: "GET /static/main-hub/ext/build/classic/theme-triton/resources/theme-triton-all_2.css HTTP/2.0", host: "pk.molgen.mpg.de", referrer: "https://pk.molgen.mpg.de/static/main-hub/ext/build/classic/theme-triton/resources/theme-triton-all.css"
```

**Comment by adRn-s** [comment]
Thanks for reporting!

We had 170 MiB of JS and CSS files that were purged recently from the repo, because our frontend had plenty of themes, but these CSS files shouldn't be required at all.

We are in the process of polishing the frontend...  looking into alternative frameworks...

In the meantime, I added empty files just to skip the issue for now, there's no CSS classes defined there that are at use in any case.

**Comment by wwwutz** [comment]
nice. I will miss the only 2 red lines in the debugger console 8-)

Thanks for fixing.
